# Generated by Django 5.2.6 on 2025-09-22 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_category_rename_item_marketitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnShopAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(max_length=50, unique=True)),
                ('created_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('previous_agreements', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=255)),
                ('days_gone_past_expiry', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='pricing.pawnshopagreement'),
        ),
    ]
