# Generated by Django 5.2.6 on 2025-09-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_pawnshopagreement_inventoryitem_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawnshopagreement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
