# Generated by Django 5.2.6 on 2025-09-22 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_pawnshopagreement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='market_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='pricing.marketitem'),
        ),
    ]
