# Generated by Django 5.2.6 on 2025-09-25 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_inventoryitem_market_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='exclude_keywords',
            field=models.JSONField(blank=True, help_text='List of keywords to ignore when scraping/creating listings', null=True),
        ),
        migrations.CreateModel(
            name='WebListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_by', models.CharField(max_length=255)),
                ('first_uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('update_count', models.PositiveIntegerField(default=0)),
                ('epos_listing_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('removed', 'Removed')], default='active', max_length=50)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_listings', to='pricing.inventoryitem')),
            ],
        ),
    ]
